import AUTH
import ENVIRONMENT
import os

# In this file, getter functions for creating parameters for all CB's
# that are used to create the samples of rocker arm for multi-objective
# shape optimization. NOTE: Only the CB parameters that are to be generated
# at script level are listed here. CB parameters like implicit bodies are 
# not listed here. TODO: Make a visualisation of CB nesting. TODO: Be sure
# to comment the CB's when there.
#
# All the JSON input and output generated by ntpcl is handled in
# nTopCaller.py. Those have to be set and modified manually for each
# CB -stage.

# --------------------------------------------------------------------------------
#                      2. Topology optimization CB (TO_CB)
# --------------------------------------------------------------------------------
# The versioning and controlling the outputs for storing is done as follows.
# The file extension is done automatically by CB export blocks,
# so no need to control that in python script level:
#
#     <dir>\\<basename>_<channel_id>_<threshold>_<material_id><.file extension>
#
# NOTE: <channel_id> is to be parsed from path in python.
# NOTE: The TO_CB does not take any path -inputs to .stp files, because
# the implicit bodies are brought from the CB_CAD_converter
# NOTE: TO_CB will export multiple meshes, and the export paths are
# constructed inside the block, from string parameters
# NOTE: Threshold values are manipulated inside CB, not in python scripts.
# This is done for the reason, that we don't have to do expensive SIMP -operations
# over and over to generate multiple meshes. Instead we get multiple meshes by
# copying 'Implicit body from TopOpt result' -block, inside our TO_CB.
#
# String variables:
#   Path_mesh_export_dir
#   basename
#   channel_id
#   material_id

# Create folder structure for channel configuration if it does not already exist
# Return: Paths to channel specific directories
def createChannelFolder(channel_id):
    pass

# --------------------------------------------------------------------------------
#               3. FE Validation, Static Structural (CB_FEA_exporter)
# --------------------------------------------------------------------------------
#
# 
